### ISSUE TITLE
remove nutrition

### ISSUE THREAD

**Issue by aeosynth** [HomebrewHomunculus/BrogueCE#25]
starving to death isn't fun. i assume food is to counter rest spam, so, remove resting heal as well, maybe change it to auto heal the first time you descend a level's stairs (falling down chasm doesn't heal).

**Comment by HomebrewHomunculus** [comment]
My personal preference is to not remove nutrition, since it adds an important time pressure. And it adds a more interesting choice for the player to make than item identification, IMO.

Roguelikes with no "free" HP regeneration and only healing upon a new floor are interesting, but IMO Brogue needs some impetus not to tarry around in a level, so it's not a great fit here.

If people want a "hungerless" mod of Brogue, then that should probably be a separate fork, since it's a fundamental change to the game loop, so I'm going to go ahead and close this issue as far as Brogue Lite goes
